from pathlib import Path
from datetime import date,timedelta
import csv,html,json
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/editorial-2026-10-08'
# title | commercial route | format | distinct decision to resolve | proof to use
ROWS='''5 web design firms for Kelowna plumbers to compare in 2027|/web-design/plumbers/|comparison|Emergency enquiries versus planned installations; service boundaries, call handling, job photos and ownership|ABC Appliance service structure; Cool Runnings qualified bookings
9 website decisions for an Okanagan business planning growth in 2027|/web-design/|checklist|Choose qualified bookings, an accountable page plan, owner access and a measurable enquiry path|All approved portfolio projects, each for its actual contribution
5 web design firms for Vernon electricians to compare in 2027|/web-design/electricians/|comparison|Separate residential repairs, panel upgrades and commercial tender enquiries; compare genuine relevant portfolios|ABC Appliance as adjacent service proof, never electrician client proof
7 things an accounting website needs before tax season|/web-design/accountants/|checklist|Capacity, client fit, document handoff and first appointment; avoid collecting tax documents through a public form|Michael's content planning and technical website delivery
5 branding services for Kelowna businesses to compare in 2027|/marketing-branding/|comparison|Strategy, identity files, rollout, copy and who executes after the logo|Upon This Rock brand development; AI Catalyst and VI films
8 ways a law-firm website can make the first enquiry easier|/web-design/law-firms/|checklist|Practice fit, lawyer credentials, conflict-check expectations and appropriate intake without sensitive case facts|Website systems experience; no invented legal-sector results
5 website partners for Okanagan hotels to compare in 2027|/web-design/hotels/|comparison|Booking-engine ownership, room detail, mobile availability, migration and ongoing seasonal editing|Okanagan Treehouse design; label adjacent accommodation proof accurately
7 website checks before your landscaping busy season|/web-design/landscapers/|checklist|Job size, service radius, garden versus maintenance enquiry, project proof and quote qualification|Cool Runnings 30% increase in qualified bookings
5 web design firms for West Kelowna builders to compare|/web-design/home-builders/|comparison|Design-build versus renovations, project photography, scope qualification and portfolio depth|Michael's design and lead-generation work, with sector distinction
6 steps to stop losing website enquiries between the form and the phone|/ai-implementation/|workflow|Acknowledge, route, collect missing information, prepare a reply, hand off and track booked work|Existing workflow demonstrations; distinguish features from measured outcomes
8 details a winery website needs before visitors plan their trip|/web-design/wineries/|checklist|Tasting reservations, groups, restaurant and retail paths, dates, access and seasonal accuracy|Treehouse visitor-journey design, no winery client claim
5 marketing partners for Vernon businesses to compare in 2027|/marketing-branding/|comparison|One-off branding versus ongoing delivery; audience research, local media, video and reporting ownership|VI positioning, AI Catalyst film, Upon This Rock identity
7 questions to ask about a vacation-rental website and direct bookings|/web-design/vacation-rentals/|buying advice|Booking engine, property detail, fees, cancellation information, channel sync and editor control|Okanagan Treehouse actual design
5 web design firms for dental practices in the Okanagan to compare|/web-design/dentists/|comparison|New-patient fit, accepted services, approachable team proof and appointment integration; verify sector work|General website experience only unless dental proof is supplied
8 things an HVAC website should make clear before summer|/web-design/hvac/|checklist|Repairs, maintenance and installations have different urgency and qualification; availability without false response promises|ABC Appliance service pages as adjacent repair example
5 website and branding partners for Okanagan charities to compare|/web-design/charities/|comparison|Donation path, campaign story, editing rights, payment fees and accessible content|St James donor work, accurately described
7 pages a physiotherapy clinic needs beyond the homepage|/web-design/physiotherapy/|checklist|Conditions versus services, practitioners, booking, practical access and useful referral information|Content structure and appointment design experience
5 social media and video services for Kelowna businesses to compare|/marketing-branding/|comparison|Who creates, who posts, platform delivery, usage rights, captions and measurement|St James donor film, AI Catalyst video, recent Vertical Impression film
9 restaurant website details that save guests a phone call|/web-design/restaurants/|checklist|Readable menus, hours, dietary questions, reservations, group enquiries and genuine current location info|Michael's content, web and visual communication work
5 web design firms for Okanagan property managers to compare|/web-design/property-management/|comparison|Owner acquisition versus tenant service, listing freshness, portal handoff and enquiries by property|General enquiry routing and website systems
7 retail website decisions before adding online checkout|/web-design/retail/|buying advice|Catalogue truth, fulfilment, local pickup, stock changes, returns information and transaction ownership|Michael's design and marketing process, no invented retail uplift
6 practical ways to use AI without handing over customer service|/ai-implementation/|checklist|Draft replies, source business facts, require approvals, stop unsupported promises and measure time saved|Custom skills and workflow demos
5 web design firms for Okanagan roofing businesses to compare|/web-design/roofers/|comparison|Emergency leaks versus full replacement, estimate qualification, project photos and service coverage|Cool Runnings for local service conversions, clearly adjacent
8 website details that help a medical practice handle appointment enquiries|/web-design/medical-practices/|checklist|Accepted patients, services, referrals, access and secure booking; no sensitive health data in public forms|General appointment and content systems; no medical efficacy claims
5 brand-development partners for West Kelowna businesses to compare|/marketing-branding/|comparison|Positioning before identity; assets for signage, website, social and sales use; scope and handover|Upon This Rock visual identity and cross-channel work
7 website improvements for a dealership beyond the inventory feed|/web-design/car-dealerships/|checklist|Vehicle availability, finance enquiry handoff, trade-in flow, service booking and inventory ownership|General web integration and conversion approach, no dealership result claim
5 website firms for Okanagan financial advisors to compare|/web-design/financial-advisors/|comparison|Practice positioning, credentials, review workflow, consultation booking and ownership; verify compliance responsibilities|Website and content experience only
8 ways to make your Okanagan business easier to understand in AI search|/web-design/|checklist|Crawl access, named services, original proof, clear location, source consistency and enquiry measurement|Google and OpenAI official guidance plus owned project evidence
5 web design firms for private schools in the Okanagan to compare|/web-design/private-schools/|comparison|Admissions journey, tour booking, parent information, staff editing and donor story|St James design and marketing, scope sourced from project
7 things to fix when your business gets enquiries for the wrong jobs|/web-design/|diagnostic|Coverage, price fit, service exclusions, enquiry fields, ad intent and follow-up quality|Cool Runnings booking result; distinguish quality from volume
5 website partners for Okanagan medical spas to compare|/web-design/medical-spas/|comparison|Practitioner credentials, treatment suitability, appointment pathways and controlled claim review|Design experience only; no invented treatment or clinic results
6 signs your business needs a new brand and 4 reasons it may not|/marketing-branding/|decision guide|Distinguish confused positioning, inconsistent assets and changed audience from a merely dated logo|Upon This Rock identity and VI positioning
5 web design firms for Okanagan appliance-repair companies to compare|/web-design/appliance-repair/|comparison|Brand and appliance coverage, fault descriptions, local booking and no false dispatch promises|ABC Appliance actual website and search work
8 questions to ask before buying a custom AI agent|/ai-implementation/|buying advice|Task, permissions, data sources, approval points, failures, handoff, monitoring and maintenance|Current custom skill and workflow portfolio
7 school website updates to make before admissions season|/web-design/private-schools/|checklist|Tour dates, application steps, fees if approved, parent questions, photography consent and staff editing|St James design and marketing work
5 video-production services for Okanagan businesses to compare|/marketing-branding/|comparison|Business objective, interview or motion needs, deliverable formats, usage rights and edit rounds|St James, AI Catalyst and VI video examples
9 details a charity donation page needs to earn confidence|/web-design/charities/|checklist|Purpose, project evidence, recipient identity, payment route, receipt information and continuing communication|St James donor story and approved campaign material
5 website partners for Vernon home-service businesses to compare|/web-design/|comparison|One-town versus regional coverage, phone enquiries, lead quality, maintenance and account control|ABC Appliance and Cool Runnings, with accurate scope
7 website changes worth making before a bigger advertising budget|/marketing-branding/|checklist|Offer match, landing page, trust, contact friction, tracking and who follows up|Cool Runnings CRO and Michael's broader marketing work
6 ways a custom AI skill differs from a prompt you paste into chat|/ai-implementation/|comparison|Reusable instructions, reference material, tools, tests, permissions and staff training|Actual reusable workflow and skill demonstrations
5 website firms for Okanagan boutique accommodation to compare|/web-design/vacation-rentals/|comparison|Distinctive imagery, practical guest questions, mobile booking, rates and owner access|Okanagan Treehouse design and visitor flow
7 local-search mistakes on otherwise beautiful business websites|/web-design/|checklist|Unclear services, missing locations, image-only answers, broken booking, duplicate pages and no useful proof|ABC Appliance structure and Cool Runnings local search work
5 branding and website partners for Okanagan professional firms to compare|/marketing-branding/|comparison|Credibility, specialist positioning, approvals, content maintenance and enquiry quality|Michael's portfolio; each competitor's actual professional-services evidence
8 ways to prepare a website project so the quote is useful|/web-design/|checklist|Objectives, pages, copy, assets, integrations, migration, ownership and support|Actual process; custom pricing not fabricated package rates
7 automations to consider before hiring for more admin|/ai-implementation/|checklist|Map repeated work, count handling time, test quality, preserve human decisions and compare maintenance|Custom workflows, with no promise to replace staff
5 website firms for Kelowna trades to compare for a 2028 rebuild|/web-design/|comparison|Compare providers on real service work, content, regional reach, enquiries and handover|Refresh all providers near November publication; include Michael
9 website handover items every Okanagan owner should receive|/web-design/|checklist|Domain, hosting, source/content export, analytics, redirects, image rights, form recipients and support|Michael's ownership and training offer
7 ways to turn one good customer story into useful marketing|/marketing-branding/|checklist|Interview evidence, written case, video cut, sales proof, service-page excerpt and consented distribution|St James film and approved Cool Runnings proof; no invented testimonial
5 signs a custom workflow is worth the maintenance cost|/ai-implementation/|decision guide|Frequency, avoidable time, error cost, integration stability and a named owner|Current implementation and maintenance offer rechecked at publication
8 numbers to review before planning next year's website budget|/web-design/|checklist|Qualified enquiries, booked work, acquisition source, response time, drop-off and ongoing costs|Owned Search Console/GA4 data only if current and approved
5 website investments to prioritise for an Okanagan business in 2028|/web-design/|priorities|Repair the highest-friction journey before a redesign; choose from real customer and business evidence|Use current annual evidence, not forecast ranking claims
7 questions for your 2028 marketing plan before choosing channels|/marketing-branding/|planning|Customer, offer, capacity, proof, budget, measurement and who does the work|Fresh year-end business priorities and portfolio proof'''

items=[]
for i,line in enumerate(ROWS.splitlines()):
 title,target,kind,angle,proof=line.split('|')
 industry=target.split('/')[-2] if target.startswith('/web-design/') and target!='/web-design/' else None
 city=next((x for x in ['West Kelowna','Kelowna','Vernon'] if x in title),'Okanagan')
 query=title.replace('5 ','').replace(' in 2027','').replace(' to compare','').replace(' firms','').lower()
 day=date(2027,1,7)+timedelta(days=7*i)
 items.append({'id':f'2027-{i+1:02}', 'publishOn':str(day),'timezone':'America/Vancouver','status':'planned','title':title,'format':kind,'city':city,'primaryQuery':query,'queryVariants':[query.replace('firms','services'),f'{industry or target.strip("/")} {city} website cost and scope',f'how to choose {industry or "a website and marketing partner"} {city}'], 'buyerDecision':angle,'primaryMoneyPage':target,'parentMoneyPage':'/web-design/' if target.startswith('/web-design/') else target,'proof':proof,'researchStatus':'Research required near publication; not a 2027 ranking finding','researchChecklist':['Search this vertical and task independently; save query/date/location and top organic URLs.','Read relevant competitor pages in full; record content structure and explicit service evidence.','Verify every listed provider against official sources and relevant work; include Michael with clear authorship.','Check technical/platform advice against current primary documentation.'],'outline':['Direct answer and recommendation summary','The buyer decision: '+angle,'A practical comparison or numbered choices, supported by current sources','What relevant work shows: '+proof,'Scope, ownership, costs to clarify and the next step','Three specific FAQs'],'faqs':[f'What should I ask a provider about {angle.split(";")[0].lower()}?',f'How should a {city} business compare the scope and ongoing costs?',f'What do I need ready before discussing {"this website" if target.startswith("/web-design") else "this project"}?'],'internalLinks':{'primary':{'href':target,'placement':'Contextual link in a relevant answer, using a specific service anchor'},'secondary':{'href':'/contact/','placement':'One closing invitation to a free consultation'},'siblings':['/blog/okanagan-website-cost/','/blog/service-business-website-checklist/'],'proofLink':'/v2/work/local-search-magnet.html' if 'Cool Runnings' in proof else '/#work'},'aeo':{'summaryWords':'45–85','faqCount':3,'targetWords':'900–1,500; stop when the decision is answered','schema':'Article, BreadcrumbList; FAQPage for visible answers; ItemList where appropriate'},'releaseGate':['research saved','Echo edit reviewed','facts and links checked','mobile/desktop verified','publication date reached']})
assert len(items)==52
assert items[-1]['publishOn']=='2027-12-30'
(ROOT/'content/resources').mkdir(parents=True,exist_ok=True)
calendar_path=ROOT/'content/resources/editorial-calendar-2027.json'
if calendar_path.exists(): items=json.loads(calendar_path.read_text())
else: calendar_path.write_text(json.dumps(items,indent=2,ensure_ascii=False)+'\n')
with (OUT/'calendar-2027.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,lineterminator='\n',fieldnames=['publishOn','title','format','city','primaryMoneyPage','buyerDecision','proof','status']);w.writeheader();w.writerows({k:a[k] for k in w.fieldnames} for a in items)
cards=''.join(f'<article><time>{a["publishOn"]}</time><div><h2>{html.escape(a["title"])}</h2><p>{html.escape(a["buyerDecision"])}</p><p><strong>Proof:</strong> {html.escape(a["proof"])}</p><a href="https://michaelmck.site{a["primaryMoneyPage"]}">{a["primaryMoneyPage"]}</a><details><summary>Article structure and release checks</summary><ul>'+''.join(f'<li>{html.escape(x)}</li>' for x in a['researchChecklist']+a['outline'])+'</ul><p><strong>Reader questions</strong></p><ul>'+''.join(f'<li>{html.escape(x)}</li>' for x in a['faqs'])+'</ul><p>Direct opening answer, current sources, contextual commercial links.</p></details></div></article>' for a in items)
(OUT/'calendar-2027.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>2027 resource calendar</title><style>body{font:17px/1.65 system-ui;background:#fafbf8;color:#1b241d;max-width:1100px;margin:auto;padding:40px 24px}h1{font-size:clamp(40px,7vw,72px);line-height:1.05;letter-spacing:-.05em}h2{font-size:24px;line-height:1.3;margin:0}article{display:grid;grid-template-columns:140px 1fr;gap:30px;padding:30px 0;border-top:1px solid #d1d8cf}time{font-weight:600;color:#365340}p{max-width:80ch}a{color:#284d39;overflow-wrap:anywhere}summary{cursor:pointer}details{margin-top:18px}@media(max-width:600px){article{grid-template-columns:1fr;gap:10px}}</style><h1>A useful article.<br>Every week of 2027.</h1><p>52 complete private articles, January 7–December 30. The manuscripts are written and linked from the canonical calendar. Publication dates remain planned slots, and time-sensitive facts are rechecked near release.</p><p>Each article supports a commercial page, relevant portfolio proof and a clear contact route. Titles and list sizes may change if the research supports a better answer.</p>'''+cards+'</html>')
print('Built the 52-week 2027 calendar from the canonical draft records.')
