import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {siteHeader,headerStyles} from './site-header.mjs';
import {markdown} from './service-discovery.mjs';
const root=new URL('../',import.meta.url);
export async function buildPrivacy(){
 const p={path:'/privacy/',heading:'Your information.',description:'How Michael McKerracher uses website enquiries, homepage preview requests, booking details and website analytics.'};
 const schema={'@context':'https://schema.org','@type':'WebPage','@id':'https://michaelmck.site/privacy/',url:'https://michaelmck.site/privacy/',name:'Privacy | Michael McKerracher',dateModified:'2026-10-09',inLanguage:'en-CA'};
 p.html=`<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy | Michael McKerracher</title><meta name="description" content="${p.description}"><link rel="canonical" href="https://michaelmck.site/privacy/"><link rel="alternate" type="text/markdown" href="/privacy/index.md"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/v2/industries/industries.css?v=2"><link rel="stylesheet" href="/v2/resources/resources.css?v=3"><link rel="stylesheet" href="/v2/privacy/privacy.css">${headerStyles}<script type="application/ld+json">${JSON.stringify(schema)}</script><script src="/assets/analytics.js" defer></script></head><body class="industry-page resource-page"><a class="i-skip" href="#main">Skip to content</a>${siteHeader}<main id="main" class="privacy-main r-frame"><header><h1>Your <em>information.</em></h1><p>This page explains how I handle information shared through michaelmck.site. I’m Michael McKerracher, an independent web design, AI implementation and marketing service provider based in Coldstream, British Columbia.</p><p class="privacy-date">Updated October 9, 2026.</p></header>
 <section><h2>When you get in touch</h2><p>The contact form asks for your name, email, message and, optionally, the service you’re interested in. The homepage design form also asks about your business, website, location, goals and timing.</p><p>I use this information to understand your request, prepare a design or recommendation, arrange a conversation and reply to you. Requesting a preview does not add you to a mailing list or commit you to a paid website.</p><p>Please leave out passwords, payment details and confidential information about your customers.</p></section>
 <section><h2>Forms, email and appointments</h2><p>FormSubmit delivers form responses to my Gmail inbox. Homepage preview requests are also stored in a private review queue on my computer. I review the design, build and delivery before a preview is sent to you.</p><p>If you open the booking calendar, Cal.com processes the information you enter to arrange the appointment. The embedded calendar loads when you choose to open it.</p><p>These providers operate under their own privacy policies and may process information outside Canada: <a href="https://formsubmit.co/privacy.pdf">FormSubmit</a>, <a href="https://policies.google.com/privacy">Google</a> and <a href="https://cal.com/privacy">Cal.com</a>.</p></section>
 <section><h2>AI-assisted design</h2><p>I use AI-assisted tools to review requests, research public business information and prepare design concepts. Request details may be processed by the AI assistant used to operate that workflow. Image-generation prompts use public business information and design requirements, rather than your private contact details or confidential customer information.</p><p>Approved website previews contain public business information. Their links are unlisted and excluded from search indexing, but they are not password protected: anyone with the link can open them. Your original enquiry is kept out of the published preview.</p></section>
 <section><h2>Website measurement</h2><p>This site uses Google Analytics to understand which pages people visit and whether they use an enquiry or booking action. Google Analytics uses cookies to distinguish visits. Google Signals and advertising-personalization signals are disabled in this site’s analytics configuration.</p><p>The form’s name, email and message are not included in the analytics events sent by the form code.</p><p>The website also keeps campaign tags, advertising click identifiers when present, the landing-page path and referring website’s hostname in your browser’s session storage. This helps identify which page or campaign led to a preview request. That context is included with a submitted preview request. The stored campaign context expires after 24 hours or when the browser clears the session.</p><p>You can manage cookies and site storage through your browser. Google also provides an <a href="https://tools.google.com/dlpage/gaoptout/">Analytics opt-out browser add-on</a>. See <a href="https://support.google.com/analytics/answer/11397207">Google’s explanation of Analytics cookies</a>.</p></section>
 <section><h2>Your choices and questions</h2><p>You can email me directly instead of using the form or calendar. To ask about your information, request a correction or deletion, or tell me you no longer want to discuss a project, email <a href="mailto:michael.mckerracher@gmail.com">michael.mckerracher@gmail.com</a>.</p><p>Enquiries and project records are held in email and the private review system. I may need to keep some records for an ongoing project, accounting or a legal obligation. I’ll explain any limits when responding to your request.</p><p>If how the website handles information changes, I’ll update this page and its date.</p></section>
 </main><footer class="r-footer r-frame"><a href="/">Michael McKerracher</a><p>Coldstream, BC. Working across the Okanagan.</p><nav aria-label="Footer"><a href="/blog/">Resources</a><a href="/web-design/">Web design</a><a href="/contact/">Contact</a><a href="/privacy/" aria-current="page">Privacy</a></nav></footer></body></html>`;
 for(const prefix of ['','v2/']){const dir=new URL(prefix+'privacy/',root);await mkdir(dir,{recursive:true});await writeFile(new URL('index.html',dir),p.html);}
 await writeFile(new URL('v2/privacy/routes.json',root),JSON.stringify([p.path])+'\n');
 await writeFile(new URL('privacy/index.md',root),`Source: https://michaelmck.site/privacy/\n\n${markdown(p.html)}`);
 return p;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)await buildPrivacy();
