"""Prepare distinct editorial briefs, preserving the earlier calendar for comparison."""
from pathlib import Path
import json, re, shutil

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/draft-library-2026-10-08'
OUT.mkdir(parents=True,exist_ok=True)
DATA=ROOT/'content/resources/draft-library'
DATA.mkdir(parents=True,exist_ok=True)
# title | slug | pillar | money page | focus | primary evidence IDs
ROWS='''
Phone calls or online forms? What works for a local service website|calls-or-forms-service-website|Conversion|/web-design/|Urgency, owner availability, call routing, minimum useful fields, acknowledgement versus booking, after-hours handling; a two-path intake example and test plan|forms,google-local
What should a small-business branding project actually include?|small-business-branding-deliverables|Brand and content|/marketing-branding/|Positioning before logo, message hierarchy, visual system, photo direction, website and social templates, file ownership; sample deliverables table and handoff questions|michael-brand
What makes a useful donor film? Start with the decision you need someone to make|donor-film-planning|Brand and content|/marketing-branding/|St James donor-film and school marketing work; beneficiary dignity, consent, specific ask, campaign landing page, captions and transcript; production brief not invented fundraising uplift|video,michael-brand
How to brief a small-business website for 2027|small-business-website-brief|Buying and ownership|/web-design/|Priority customer action, service hierarchy, real assets, existing URLs, integrations, editing owner, budget assumptions, sign-off; completed sample brief for hypothetical electrician clearly presented as an example|google-starter
Website subscription or upfront build? Compare the whole cost|website-subscription-vs-upfront-build|Platforms|/web-design/|Setup, ongoing changes, domain, hosting, seats, support, cancellation, content ownership and migration; worked arithmetic using explicitly hypothetical CAD amounts, not market rates|framer-price,webflow-price,wordpress
What to decide before paying for an AI workflow|before-buying-ai-workflow|AI and operations|/ai-implementation/|Choose repeatable work, baseline the task, sources and permissions, exception route, human approval, maintenance ownership; practical enquiry triage example; Michael audit CAD900 and custom systems from2500/month only if relevant|michael-ai
Holiday hours: the website changes that prevent wasted calls and visits|holiday-hours-website-checklist|Local discovery|/web-design/|Google special hours, website service availability, form acknowledgement, booking calendar, voicemail; test the holiday customer journey; do not imply GBP hours update website automatically|google-hours,google-local
What you should receive when your new website is handed over|website-handover-checklist|Buying and ownership|/web-design/|Domain/admin ownership, source and content export, renewal record, analytics, backups restore, form recipient, edit training, account revocation; practical owner acceptance checklist|webflow-export,framer-export,wordpress
What works on a plumber website? A 2027 plan for better enquiries|plumber-website-design|Industry websites|/web-design/plumbers/|Emergency versus planned work, service area by job type, truthful answer hours, drain and heater scope, job photography, dispatcher handoff; sample page architecture; Kelowna/West Kelowna/Lake Country only where actually served|google-local,google-starter
Framer vs Webflow vs a custom website: what should a small business choose?|framer-webflow-custom-website|Platforms|/web-design/|Separate visual builder, CMS and hosting; Framer design-led editing, Webflow class-based design and collections, custom static/headless control; compare who edits, content relationships, booking integration, recurring cost, exit cost; no platform universal SEO winner|framer-cms,framer-export,webflow-cms,webflow-export,sanity-intro
What works on an electrician website beyond a list of services?|electrician-website-design|Industry websites|/web-design/electricians/|Emergency faults versus planned panels/EV chargers/renovations; scope, verified credentials for actual contractor, site assessment, strata/commercial intake, photos of finished work; no electrical how-to or blanket licence claims|tsbc,google-starter
An accounting website that attracts the clients you want|accountant-website-design|Industry websites|/web-design/accountants/|Personal tax versus bookkeeping/advisory, business stages, client fit, deadlines owner supplies, secure-document handoff outside enquiry form, team bios and engagement process; no invented CRA dates|privacy,forms
How to choose a branding partner for a Kelowna small business|kelowna-branding-partners|Brand and content|/marketing-branding/|Owned comparison including Michael, Twin Creek Media, Svice based on official service scope; clear authorship; compare identity-only, website launch and ongoing campaign need; concrete scope questions, no ranked awards or fabricated rates|michael-brand,twincreek,svice
What works for law-firm websites in 2027?|law-firm-website-design|Industry websites|/web-design/law-firms/|Practice-specific pages, lawyer credentials/bios, office/remote meeting arrangements, first-conversation expectations, limited safe intake and conflict review; calm credibility not aggressive leads language; BC marketing rule 4.2 accuracy; no case outcome promises|bc-law,privacy,forms
A hotel website should make booking feel straightforward|hotel-website-direct-booking|Industry websites|/web-design/hotels/|Room differences, occupancy, accessibility details, cancellation terms from property, actual photography, date handoff, booking-provider consistency; keep attribution across booking engine; Okanagan visit planning via tourism sources|tourism-kelowna,hotel-links,google-starter
Prepare your landscaping website before the busy season|landscaping-website-seasonal-demand|Industry websites|/web-design/landscaping/|Maintenance contracts versus one-time projects, coverage, before/after scope, quote readiness, booking capacity, seasonal calendars verified with owner; Cool Runnings 30% qualified bookings only supported metric|cool,google-local
Framer for small-business websites: where it fits and where it gets awkward|framer-small-business-websites|Platforms|/web-design/|Visual editing, CMS structure, forms, redirects, staging and ownership; distinguish managed publishing from export and rebuild limitations; verify current portability docs not assume no export|framer-cms,framer-export,framer-price
From website enquiry to booked work: fix the handoff|website-enquiry-follow-up|Conversion|/ai-implementation/|Form delivery, named owner, acknowledgement, queue, response capacity, qualify then book; retry and duplicates, privacy, human confirmation; mock workflow explanation no claimed implemented client process|forms,michael-ai
What a winery website needs before someone plans a visit|winery-website-visitor-planning|Industry websites|/web-design/wineries/|Tastings/reservations, food, group policies, transport, accessibility, seasonal availability, map/location, direct product shopping only if offered; West Kelowna official wine context; do not invent alcohol legal rules|tourism-west,google-hours
Webflow for small businesses: when its CMS and design control are worth it|webflow-small-business-websites|Platforms|/web-design/|Classes/components, CMS collections, editor permissions, site versus workspace bill, managed hosting, export with feature exclusions, editor training; sample services/team/projects model|webflow-cms,webflow-export,webflow-price
A vacation-rental website that earns the direct-booking enquiry|vacation-rental-direct-booking-website|Industry websites|/web-design/vacation-rentals/|Actual accommodation visuals, bed configuration, parking/access, house rules, dates, price completeness, booking handoff; Treehouse design only not invented conversion outcome; do not give licensing law advice|treehouse,tourism-kelowna
What makes a dental website reassuring and useful?|dental-website-design|Industry websites|/web-design/dentists/|New patient versus existing booking, treatment overview, named clinicians, location/access, questions about fees and coverage answered without invented promises; use secure clinical systems for health details|privacy,forms
What an HVAC website needs before a customer calls|hvac-website-design|Industry websites|/web-design/hvac/|Repair/maintenance/replacement separate routes, installed brands only verified, service zones, real after-hours availability, financing terms verify, quote assumptions, technical credentials owner verified; no savings claims or repair instructions|tsbc,google-local
WordPress, Webflow or a custom CMS for a charity website?|charity-website-platforms|Platforms|/web-design/charities/|Donations external provider, resource library, volunteers/many editors, restricted roles, editorial review, integrations and support; compare ownership maintenance and ease not assume free total; St James design/marketing and RCCV community content|wordpress,webflow-cms,sanity-intro,privacy
A physiotherapy website should help someone choose their first appointment|physiotherapy-website-design|Industry websites|/web-design/physiotherapy/|Care offered, practitioner fit, clinic access, appointment duration suppliedbyclinic, fees and insurance questions, booking handoff, safe intake; educational content not medical advice|privacy,forms
What belongs on your website, social media and in a video?|website-social-video-content|Brand and content|/marketing-branding/|Website durable sourceoftruth, social discovery, video explains, campaign link closes; VI explains a misunderstood medium, AI Catalyst video, St James film; content repurposing plan with consent|michael-brand,video
Restaurant websites: help guests decide, then get out of the way|restaurant-website-design|Industry websites|/web-design/restaurants/|Readable HTML menu not PDF-only, current hours, reservation versuswalkin, takeout link, group enquiry, dietary-info confirmation, actual food photos, parking/access; no fake menu prices|google-hours,wcag
What a property-management website needs for owners and tenants|property-management-website-design|Industry websites|/web-design/property-management/|Separate owner sales journey from tenant support, listings availability, maintenance emergencyroute, portal links, coverage, managementscopeandfeequestions, secureapplications; no legal tenancyclaims|privacy,forms
Shopify, WooCommerce or a simple catalogue? A retailer's website decision|retail-website-platforms|Platforms|/web-design/retail/|Inventory source, in-store and online stock, pickup/delivery, payments, product information, returns; Shopify managed commerce versus Woo onWordPress operations; catalogue-firstwhencheckoutnotready|shopify,woo,wordpress
AI on a service-business website: start with useful work|ai-service-business-website|AI and operations|/ai-implementation/|Draft/routeenquiries, summariseapprovedknowledge, helpstaffanswer, monitorhandoffs; distinguish assistant/adviser/customagent from autonomouscommitments; permissions, exceptions, logs; no AI chatbot slappedoneverypage|michael-ai,google-ai
What makes a roofing website credible before the site visit?|roofing-website-design|Industry websites|/web-design/roofing/|Roof types and serviceareas, repairvsreplacement, job photos/context, inspectionprocess, warrantytermsasverified notblanketguarantee, urgentleakcontact, insurancecredentialsverification|google-local,google-starter
Medical-practice websites: make the next step clear without collecting too much|medical-practice-website-design|Industry websites|/web-design/medical-practices/|Acceptingpatientsstatus supplied, caremodel, appointmentdirections, referrals ownerdefined, accessibility, secureclinicalportal; minimal publicform data; noclinicaladvice/guaranteedprivacyorlegalcompliance|privacy,wcag,forms
What makes a small-business website look good? A practical design critique|good-small-business-website-design|Design|/web-design/|Hierarchy,type,contrast,spacing,realphotos,consistentcomponents,clearCTA; compare actual ABC,Treehouse,RCCV decisions without pretendingmetrics; aestheticqualityplus taskcompletion; actionablebefore/after copy example|michael-web,wcag
A car-dealer website needs more than an inventory feed|car-dealer-website-design|Industry websites|/web-design/car-dealers/|Vehicleconditionandactualphotos, update/inventoryowner, testdriveenquiry, tradeindetails, financeinsecureapprovedsystem, mobilefiltering, legitimatefeesfromdealer; nospecificcreditterms|privacy,google-starter
A financial-advisor website should help the right client recognise the fit|financial-advisor-website-design|Industry websites|/web-design/financial-advisors/|Servicemodel, clientstage, qualificationsverified, clearmeetingprocess, nospecificinvestmentreturnsorpromises, providercompliancereview, secureinformationhandoff; educationalwebadvice only|privacy,forms
How a small-business website can be easier to find in Google and AI search|small-business-ai-search|Local discovery|/web-design/|Contentfacts/entities, crawlability, internalnavigation, ownedproof and author, GoogleAIrequirements, no specialAIschemaor llmstxtrankboost, OAISearchBotvsGPTBot distinctions; actual FAQ answers; measurementwithout inventedcitationlift|google-ai,google-helpful,openai-bots
Sanity explained for a business owner: CMS, website and hosting are different jobs|sanity-small-business-cms|Platforms|/web-design/|StructuredcontentandStudio, frontendneeded, managedContentLake, selfhostableStudio doesnotselfhostContentLake, previewconfigured, rolesandtraining, exportanddevelopersupport; when unnecessaryfor5pages|sanity-intro,sanity-host,sanity-export
Getting the wrong enquiries? Your website may be attracting the wrong work|website-wrong-enquiries|Conversion|/web-design/|Serviceboundaries, minimumscopeonlywhenownertrue, areas/fit, timeframe, contentmatch, qualificationform; recordwhydeclined and changeprioritypage; avoid promisingleadqualityfromcopy alone|forms,cool
Medical-spa websites: balance visual appeal with clear treatment information|medical-spa-website-design|Industry websites|/web-design/medical-spas/|Providercredentials, treatmentconsultationpath, consentandphotography, costquestions scopeprovided, avoid outcomeclaims, clinicianreview; brandtrustandminimalintake; no medicalefficacy advice|privacy,wcag
Do you need a new brand, a better website or clearer words?|rebrand-redesign-or-copy|Brand and content|/marketing-branding/|Diagnosebrandmisfitvs UXvsunclearoffer; specific symptoms/lowestusefulintervention; UponThisRock identity,StJamesstory,VIcategoryexplanation; don't invent clientsurveys|michael-brand,michael-web
What works for appliance-repair websites? Lessons from ABC Appliance|appliance-repair-website-lessons|Industry websites|/web-design/appliance-repair/|Appliancecategories, supportedbrands verifiedbybusiness, serviceareas, bookinginfo, optionalmodeldescription, landlord/householderroutes; ABC increasedconsistentsearchvisibility userreported no numericperiod; differentiate siteproof from proposedimprovements|abc,google-local
Custom-built or self-hosted? What website ownership really means|self-hosted-custom-website-ownership|Platforms|/web-design/|Codeownership, domain,content, hosting, backups, runtimeupdates, formmail, analytics; managedstaticdeploymentstillcustomwithoutserveradmin; cost/exitplan; selfhostSanityStudio distinctionifneeded|wordpress,webflow-export,sanity-host
A private-school website that helps families take the next step|private-school-website-design|Industry websites|/web-design/private-schools/|Age/programmefit, curriculumreal, admissionssteps, visiting, feesfromschool, safeguardingprivacy, parentcurrentresourcesseparatefromprospective; StJamesdesignmarketing proof no enrolmentclaim|privacy,wcag,michael-brand
Website photography, video or animation: which earns its place?|website-photography-video-animation|Design|/web-design/|Stillimageimmediateproof, videoprocess/emotion, animationrelationships; userchoice/reducedmotion/weight/posters/captions; TreehousescrollvsABCinformation,VIexplainermedium; avoid animationsforfiller|wcag,video,web-vitals
What a charity donation page needs before asking for money|charity-donation-page|Industry websites|/web-design/charities/|Specificpurpose, trustedorganisationidentity, donationprocessor, recurringchoice, receiptsprocessascharityverified, beneficiaryconsent, plainprivacy, mobilehandoff; StJamesfilm supportsmission notverifieddonationlift|cra-charity,privacy,forms
Framer vs Webflow for local SEO: what actually affects the result?|framer-webflow-local-seo|Platforms|/web-design/|Crawlableusefulpages,titles/headings,redirects,canonicals,performance,structureddataaccuracy, contentwork; compareeditablecontrolswithofficialdocs; platformcannotguaranteeranks; concrete prelaunchchecknotwholecomparisonduplicate|framer-seo,webflow-seo,google-starter,google-ai
Before buying more ads, check whether your website can use the traffic|website-before-paid-ads|Conversion|/web-design/|Intentmatch, specificlandingpage, localproof, phoneformhandoff, consenttracking, dedupedqualifiedleads, simpleCACsamplehypotheticalCAD; noforecastfromindustryaverage; user15/dayoptionalhypotheticalnotactualcampaign|ga4,forms,cool
Custom AI skills versus prompts: what changes for a small team?|ai-skills-versus-prompts|AI and operations|/ai-implementation/|Instructions plusreferencefiles procedure, repeatability vsuncontrolledpaste, toolspermissions separate, testcases/approval, owners; writerbriefskill or intakeclassification example, no vendorimplementationguarantees|michael-ai
Boutique accommodation design: show the stay people are choosing|boutique-accommodation-website-design|Design|/web-design/vacation-rentals/|Treehouserealdesignanalysis, roomscale/location/context, desktopstoryandmobilebooking, photography/copy relevance, clear availability handoff; warmdistinctdesign versus templatehotel; noimaginaryA/Btests|treehouse,tourism-vernon,wcag
Location pages that help customers instead of repeating a city name|useful-location-pages|Local discovery|/web-design/|Sameoperatorservicearea distinctfromfakeoffices, localjobdetails, genuinecoverage/exclusions, access/deliveryplans, internalserviceconnections, avoiddoorways; KelownaWestKelownaVernon legitimatecontext; Coolstrategy|google-spam,google-local,cool
What works on a professional-services homepage?|professional-services-homepage-design|Design|/web-design/law-firms/|Positioningforlawaccountingadvisory, calm authority, specificfit, realbios/process, clearconsultation, typography/constrainedmotion; nofakeawards/reviews; threehomepageopeningexamples withoutclaimingclientwork|wcag,bc-law
How to compare website quotes without choosing on price alone|compare-website-quotes|Buying and ownership|/web-design/|Identicalbrief, copyandmedia deliverables, migration/redirects, integrations, accessibility, analytics, hosting/ownership, support andexclusions; scoredcomparisonworksheetno arbitraryscorespretendingtested|webflow-export,forms,google-starter
What work should you automate before adding more admin?|automate-before-more-admin|AI and operations|/ai-implementation/|Frequency/variation/risk/exception matrix; enquiryack, reminders, approvedcontentreuse, briefcreation, reportassembly; human approval forcommitments; timebaselineandmaintenancecost not staffdisplacementpromise|michael-ai,privacy
Templates or custom design: when is a tailored website worth it?|template-vs-custom-website|Design|/web-design/|Contentfitversusvisualnovelty, reusecomponentsgood, customserviceflow/integrations, accessibility/performance; designcustomdoesnotmeanCMSfromscratch; diagnoseconstraint; ABC/Treehouserelevant differences|michael-web,wcag
Who should update your website after launch?|website-editing-training|Buying and ownership|/web-design/|Ownereditroutinefields, designerlayouts, developerintegrations; accessroles/staging/approval/rollback; practicaltrainingexercisesforhoursprojectnewservice; supportscopeandresponsibilitymatrix|framer-cms,webflow-cms,sanity-intro
Turn one real customer project into useful website content|customer-project-content|Brand and content|/marketing-branding/|Permission, briefproblem/constraints/work/result, realimagesnotfabricatedreviews, service+localpage placement, video/socialderivatives, no attributionswecan'tprove; Coolbooking30%countscope andABCqualitative|cool,abc,video
When does a custom workflow justify ongoing maintenance?|custom-workflow-maintenance|AI and operations|/ai-implementation/|BusinessownerROIworksheettimefreed/errorreduction costnotguarantee, integrationschange, logs/permissions/fallback, responseresponsibility; Michael2500/monthstarting builddesignmaintenance scope; offtheshelfmayenough|michael-ai
What should you measure before next year's website budget?|website-measurement-budget|Conversion|/web-design/|Viewsintentqualifiedenquiriesacceptedjobsprofitcapacity; phoneclicknotcall; formsubmittednotsale; GA4keyevents SearchConsolequeries andcustomerrecord join; samplemonthlyscorecardclearlyexample|ga4,gsc,cool
An accessible website is easier to use: practical checks for a small business|small-business-website-accessibility|Design|/web-design/|Keyboardfocus, labels/errors, contrasttextsize/reflow, altnotkeywordstuff, motionchoice, captions, authentic tasktest; WCAG reference not claimlegalcertification, explicitchecks versus automatedauditonly|wcag,forms,video
Your next website plan: choose the customer problem before the channel|small-business-website-growth-plan|Buying and ownership|/web-design/|Annualprioritiesdemand/conversion/followup/retention choosebottleneck, onepageplan withownermeasurementreview; industrydifferencesplumberlawhotel, avoid newyearfreshnessfluff; linkotherguideswhenlive|google-helpful,cool,michael-ai
'''

if __name__=='__main__':
    old=[]
    for year in ['2026','2027']:
        p=ROOT/f'content/resources/editorial-calendar-{year}.json'
        backup=OUT/f'original-calendar-{year}.json'
        if not backup.exists():shutil.copy2(p,backup)
        old+=json.loads(backup.read_text())
    rows=[x.strip().split('|') for x in ROWS.strip().splitlines()]
    assert len(rows)==len(old)==60,(len(rows),len(old))
    briefs=[]
    for i,(row,prior) in enumerate(zip(rows,old)):
        title,slug,pillar,money,focus,evidence=row
        b={**prior,'id':f'draft-{i+1:02}','slug':slug,'title':title,'pillar':pillar,'status':'drafting','originalTitle':prior['title'],'primaryMoneyPage':money,'primaryQuery':title.rstrip('?'),'queryVariants':[title.rstrip('?'),title.split(':')[0]+' Kelowna Okanagan'],'buyerDecision':focus,'sourceIds':evidence.split(','),'researchAsOf':'2026-10-08','releaseGate':['draft reviewed','time-sensitive facts rechecked near release','publication date reached'],'internalLinks':{'primary':money,'parent':'/web-design/','contact':'/contact/'},'wordTarget':'1100–1600 useful words; compare decisions with specific examples, not padding'}
        briefs.append(b)
    (OUT/'briefs.json').write_text(json.dumps(briefs,ensure_ascii=False,indent=2)+'\n')
    print(f'Prepared {len(briefs)} distinct briefs')
