"""Replace unsupported technical and professional-sector assertions after source review."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'content/resources/draft-library';DOC=ROOT/'docs/draft-library-2026-10-08'
events=[]
def save(a,reason):
    a['wordCount']=len(html.unescape(re.sub('<[^>]+>',' ',' '.join([a['summary']]+[s['title']+' '+s['body'] for s in a['sections']]+[' '.join(x) for x in a['faqs']]))).split())
    a.setdefault('mainEditorEdits',[]).append({'reason':reason,'date':'2026-10-08'})
    a['criticalFactsReviewed']=True
    (DATA/(a['slug']+'.json')).write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');events.append(a['slug'])
def article(slug):
    p=DATA/(slug+'.json')
    if not p.exists():return None
    a=json.loads(p.read_text())
    return a if 'editorialReview' in a and not a.get('criticalFactsReviewed') else None
a=article('law-firm-website-design')
if a:
    a['summary']='A law-firm website should help a prospective client recognise the right practice area, understand the lawyer’s experience and make an appropriate first enquiry. For an Okanagan firm planning its 2027 site, the useful priorities are clear service pages, verifiable professional information, accessible contact paths and an intake process reviewed by the practice.'
    for s in a['sections']:
        if s['id']=='content-that-carries-weight':
            s['body']='<p>A useful law-firm website gives the homepage, lawyer profiles, practice-area pages and contact page separate jobs. Start with the firm’s actual services and how prospective clients are referred or find it.</p><p>The homepage should make the practice areas and office location easy to identify. A lawyer profile should explain current responsibilities, relevant experience and professional qualifications in language a prospective client can understand. Include a recent photograph, an accurate role and the correct route for an enquiry. There is no useful universal rule for biography length; give the reader enough information to assess fit.</p><p>Practice-area pages should explain the kinds of matters the firm accepts, the first step, how an initial conversation is arranged and what the visitor should avoid sending through a public form. For a Vernon office serving the wider Okanagan, explain the available meeting arrangements and any genuine geographic limits. Do not imply an office in every community served.</p><p>Treat testimonials as a separate compliance decision. A review being visible on a third-party platform does not make it automatically suitable for republication in the firm’s marketing. The Law Society’s advisory specifically distinguishes unsolicited third-party reviews from marketing the lawyer reproduces or refers to.</p><p>Keep contact details visible and make forms usable with clear labels, instructions and helpful errors. The <a href="https://www.w3.org/WAI/tutorials/forms/">W3C accessible forms guidance</a> is a practical reference for those interface choices.</p>'
        if s['id']=='a-safe-enquiry-form-sample':
            s['title']='An initial enquiry form the practice can review'
            s['body']='<p>A public law-firm enquiry form should begin the contact process without inviting a detailed account of the matter. The practice should decide which fields belong on that first form and which belong in its controlled intake process.</p><ul><li><strong>Name and contact method:</strong> enough to arrange a response.</li><li><strong>Broad practice area:</strong> for example, the categories the firm actually handles.</li><li><strong>Meeting preference:</strong> phone, video or office visit where offered.</li><li><strong>Short non-sensitive note:</strong> with clear instructions to leave out detailed facts and documents.</li><li><strong>What happens next:</strong> the practice’s approved explanation of response expectations and when a lawyer-client relationship is established.</li></ul><p>Conflict checks may need additional identities or matter information. Let the firm decide how to request and safeguard those details instead of adding them to an ordinary public form by default. Test the route with a dummy enquiry, then confirm who receives it and how the appropriate staff member responds.</p>'
        if s['id']=='how-ai-changes-the-technical-baseline':
            s['title']='What Google and AI search need from the website'
            s['body']='<p>The technical foundation for a law-firm website is clear, accessible content that search systems can reach and understand. <a href="https://developers.google.com/search/docs/appearance/ai-features">Google’s guidance on AI features</a> says the usual SEO fundamentals apply; pages need to be indexed and eligible to appear with a snippet. There is no special AI schema or new machine-readable file required for inclusion.</p><p>Give each practice-area page a descriptive title, a clear main heading, an answer to the visitor’s likely question and useful internal links. Publish important information as readable page text, rather than making a brochure image or PDF the only source. Keep office details and lawyer profiles current.</p><p>Measure the pages that attract relevant enquiries and discuss those enquiries with the intake team. Neither a particular response-time threshold nor a collection of reviews guarantees an AI recommendation. Improve loading and accessibility because they help people use the site, and keep search claims tied to results the firm can actually observe.</p>'
        s['body']=s['body'].replace('Attorney','Lawyer').replace('attorney','lawyer').replace('Blog, FAQs, practice-area articles, reviews','Resources, FAQs and practice-area explanations').replace('Search engines, AI summaries, new clients','New clients arriving through relevant searches').replace('attorneys lose steam quickly when they try to write marketing copy between client obligations','lawyers need time to review accuracy and scope alongside their client work')
    a['faqs'][0]=['Should every lawyer profile include a full curriculum vitae?','Start with the lawyer’s current role, relevant experience and verified qualifications. Link a fuller CV separately if that helps the intended audience. A person choosing a lawyer should not have to extract the practice fit from an undifferentiated list of achievements.']
    a['faqs'][1]=['Can British Columbia lawyers use client testimonials on their websites?','Do not assume an ordinary customer testimonial is suitable. The Law Society’s marketing advisory requires the content to be true and verifiable and identifies subjective praise as a problem under the rule. The practice should review each proposed testimonial and its context before use; a review on a third-party platform is a different situation from republishing it in the firm’s own marketing.']
    a['sources'].append({'name':'Google Search: AI features and your website','url':'https://developers.google.com/search/docs/appearance/ai-features'})
    a['editorial']['sourceUse'].append({'url':'https://developers.google.com/search/docs/appearance/ai-features','claim':'Normal SEO and index/snippet eligibility apply to Google AI features; no special AI markup is required.'})
    a['editorial']['claimsToRecheckBeforeRelease'].append('Recheck current BC professional marketing guidance and have the practice review its own intake and claims.')
    save(a,'Removed unsupported biography traffic and AI latency claims; corrected testimonials and first-contact intake; added official Google source and Okanagan operating details.')
a=article('framer-small-business-websites')
if a:
    for s in a['sections']:
        if s['id']=='cms-limits':
            s['title']='The CMS questions to test with your actual content'
            s['body']='<p>Evaluate Framer’s CMS with the content you intend to maintain. Its <a href="https://www.framer.com/cms/">current CMS page</a> describes collections, dynamic filters, conditional visibility and built-in localization. A blanket claim that Framer cannot support multilingual CMS content would therefore be a poor basis for choosing a platform.</p><p>Map the relationships you need: services linked to projects, articles linked to authors, or locations linked to the relevant services. Build one example of each important relationship and check how an editor creates, updates and previews it. If you publish in more than one language, test the translation and approval workflow with a real page.</p><p>Recovery is another practical question. Ask the provider to show what happens after an accidental edit or deletion, what can be restored and who has permission to do it. For integrations, demonstrate the actual import, export or external connection you need rather than assuming either that every connection is supported or that no API exists.</p><p>Plan limits and feature availability can change. Match the current plan to the expected collections, items, editors and publishing workload, and record the ongoing cost in the proposal. The result should be a working content model and a clear support arrangement.</p>'
        if s['id']=='decision-framework':
            s['body']='<p>Choose Framer when the visual workflow suits your team and a trial with your real content supports the way you expect to publish. It can be a candidate for a service website, project portfolio or resource library. Judge the editor experience, mobile layout, form connection and content structure together.</p><p>Compare other approaches when your requirements are centred on unusual integrations, several publishing channels or a highly tailored content model. A headless CMS may suit content that needs to feed more than one frontend. A custom build may suit a specialised workflow. Those are reasons to compare a concrete implementation, not automatic reasons to rule Framer out.</p><p>Try a common owner task before choosing: add a project, connect it to the appropriate service, update the photograph and publish it. Then ask how the same content could be exported and maintained if the business moved platforms. A polished demonstration is useful only if the people responsible for the live site can repeat the work.</p><p>To compare the buying models, read about <a href="/blog/okanagan-website-cost/">Okanagan website project costs</a> and <a href="/blog/website-subscription-vs-upfront-build/">subscription versus upfront website costs</a>. Include content preparation, integrations, training and continuing support in the comparison.</p>'
        s['body']=s['body'].replace('If yes, test the localization options or plan for an external tool.','If yes, demonstrate the built-in localization workflow and confirm the current plan and translation needs.').replace('The lowest plan is rarely the right one if you are serious about content.','Choose from the actual publishing requirements rather than assuming the cheapest or most expensive plan is the right one.')
    a['faqs'][0]=['Can I use Framer for a business blog?','Yes. Framer supports CMS collections and designed templates for repeated content such as articles. Define the fields you need, try the editing and preview process, and check current plan limits and recovery arrangements before launch.']
    save(a,'Replaced unsupported CMS restrictions with current official features and concrete buyer acceptance checks; removed invented lack of localization, APIs and item recovery.')
a=article('webflow-small-business-websites')
if a:
    for s in a['sections']:
        if s['id']=='costs-billing':
            s['title']='Compare the whole publishing cost'
            s['body']='<p>Webflow separates Site plans from Workspace plans. The right setup depends on hosting, CMS needs, editing access and collaboration. Ask for a line-by-line proposal using the current plans rather than selecting a tier from an old comparison article.</p><table><caption>What to include in the Webflow cost comparison</caption><thead><tr><th>Requirement</th><th>What to confirm</th><th>Why it changes the decision</th></tr></thead><tbody><tr><td>Public website</td><td>Custom domain, traffic needs and the appropriate Site plan</td><td>The live website needs a supported hosting arrangement</td></tr><tr><td>Content library</td><td>Collections, expected items and required publishing features</td><td>The site must accommodate the real publishing workload</td></tr><tr><td>People editing</td><td>Who edits, who designs, who publishes and how access is billed</td><td>A working team arrangement matters more than a headline plan price</td></tr><tr><td>Connected services</td><td>Booking, forms, payments, email and any other integrations</td><td>These may have separate costs and support responsibilities</td></tr><tr><td>Exit plan</td><td>Code and content export, replacement forms and future editing</td><td>Moving requires more than downloading the design</td></tr></tbody></table><p>Include the build, content preparation, staff training and ongoing changes alongside platform charges. My <a href="/blog/okanagan-website-cost/">Okanagan website cost guide</a> explains how to compare the wider project scope.</p>'
        s['body']=s['body'].replace('and then add as many as you like without rebuilding pages','and then add items within the chosen plan’s limits without redesigning each page').replace('If you do, the CMS plan is usually the right entry point. If you do not, a Basic plan or even a custom static build might be enough.','Choose a current Site plan that supports those collections. If no CMS is needed, compare a simpler hosted setup and a custom static build on total cost and editing needs.').replace('The most common mistake I see is a business paying for a higher tier than their content actually requires.','Compare the actual content requirements with the proposed plan before committing.')
    save(a,'Replaced changeable plan-name table and invented common-client anecdote with a cost worksheet; corrected unlimited-CMS implication.')
a=article('charity-website-platforms')
if a:
    fixes=[('you own your content and your data outright','your organisation can control its content and database under the agreed hosting and access arrangement'),('You own the software, content and data, and can move hosts freely','Open-source software with exportable content and database; check licences and dependencies'),('Typically the strongest ownership, since content is structured and stored separately from presentation','Depends on the CMS, contract, export options and frontend dependencies'),('For a charity whose website is how programs get delivered, it is often the only approach that stays tidy.','For a charity whose website supports programme delivery, compare the proposed custom workflow with a carefully configured existing platform.'),('Best fit for dependable, custom integrations with a CRM, payments and email','Can be tailored to the required CRM, payments and email connections'),('at a fraction of the cost','with a smaller implementation scope'),('If mistakes are a constant risk, that is a sign to consider a custom CMS with a real approval step.','If mistakes recur, review permissions, training and approval steps in the existing platform before assuming a replacement is necessary.'),('wants to own everything','wants control of its content and hosting')]
    def replace(v):
        if isinstance(v,str):
            for old,new in fixes:v=v.replace(old,new)
            return v
        if isinstance(v,list):return [replace(x) for x in v]
        if isinstance(v,dict):return {k:replace(x) for k,x in v.items()}
        return v
    for k in ['summary','takeaways','sections','faqs']:a[k]=replace(a[k])
    save(a,'Separated content ownership from software licences and managed dependencies; removed sole-option and unsupported relative-cost claims.')
a=article('charity-donation-page')
if a:
    a['summary']='A useful donation page makes the case for giving, explains what the gift supports and lets someone complete the payment without confusion. For an Okanagan charity, that means a specific campaign story, clear one-time and monthly options, an accessible form, accurate receipt information and a helpful acknowledgement after the gift.'
    first=a['sections'][0];first['title']='Start with the reason to give';first['id']='start-with-the-reason-to-give'
    first['body']='<p>A donation page should answer the donor’s decision before asking for payment: what needs to happen, why does it matter and how will the gift help? A strong photograph or short film can make that purpose tangible, but the surrounding page must still explain the appeal for someone who does not press play.</p><p>Use a specific, current description of the programme or campaign. If you show a target, progress figure or example of what a contribution funds, confirm the basis with the organisation and assign someone to keep it current. Do not manufacture a neat cost-per-outcome claim just to fill a giving card.</p><p>For example, an Okanagan community charity might put a short account of the current need above the form, then show the programme being funded, the permitted use of gifts and a named contact for larger or unusual gifts. The point is a coherent decision path. My <a href="/web-design/charities/">website design for charities</a> approach connects that story to the actual donation process.</p><table><caption>A donation page content map</caption><thead><tr><th>Part of the page</th><th>What the donor needs</th></tr></thead><tbody><tr><td>Opening</td><td>A clear need and a specific reason to support the work</td></tr><tr><td>Evidence</td><td>Current programme information, appropriate imagery and substantiated progress</td></tr><tr><td>Giving choices</td><td>Amount, one-time or monthly frequency and any genuine designation options</td></tr><tr><td>Payment</td><td>An accessible, recognisable payment flow with clear errors and confirmation</td></tr><tr><td>Receipt and follow-up</td><td>Accurate eligibility and timing information, acknowledgement and a contact for help</td></tr></tbody></table>'
    second=a['sections'][1];second['title']='Explain receipts accurately without making tax promises'
    second['body']='<p>Confirm the organisation’s receipt eligibility and actual process before adding receipt promises to the donation page. The <a href="https://www.canada.ca/en/revenue-agency/services/charities-giving/charities/operating-a-registered-charity/issuing-receipts/sample-official-donation-receipts.html">CRA’s sample official donation receipts</a> show that the receipt information depends on the kind of gift and any advantage received.</p><p>The website should state what the organisation can confirm: whether a receipt is available, how it is delivered, when to expect it and whom to contact if it is missing. A fundraising event or non-cash gift needs its own reviewed wording. Avoid promising a donor-specific tax outcome or presenting every payment as fully receiptable.</p><p>Keep that explanation close enough to the form to be useful. A donor should not have to search a policy archive to understand the organisation’s process.</p>'
    for s in a['sections']:
        s['body']=s['body'].replace('all reduce abandonment','help people understand and complete the form').replace('One-time giving, monthly giving, and sometimes securities or in-kind giving cover most donor intent.','Start with the giving methods the organisation actually supports, such as one-time and monthly gifts. Offer a contact route for other gifts if the organisation is equipped to handle them.').replace('complete a test donation','complete a test donation')
    a['sections'][-1]['body']+='<p>If you want help connecting the campaign story, page design and donation flow, <a href="/contact/">get in touch</a> and we can define the right scope for your charity.</p>'
    save(a,'Restored donor decision and campaign purpose ahead of receipt mechanics; removed oversimplified tax-outcome advice; added practical page map and requested service/contact paths.')
a=article('framer-webflow-local-seo')
if a:
    a['summary']='Framer and Webflow can both support a local business website with useful service pages, clear headings and crawlable content. Choose by testing the actual publishing work: service updates, project pages, redirects, metadata and mobile layouts. Neither platform supplies local expertise or guarantees search results. Your content model, implementation and ability to maintain accurate information are the more useful comparison.'
    for s in a['sections']:
        if s['id'] in ['where-platforms-differ','platform-differences'] or s['title']=='Where the platforms actually differ':
            s['body']='<p>Both platforms offer SEO controls and a CMS, but their editing and design workflows differ. Compare the work your team will actually do rather than assigning one tool to “small sites” and the other to “serious SEO.”</p><p>Framer’s <a href="https://www.framer.com/seo/">SEO overview</a> and Webflow’s <a href="https://webflow.com/seo">SEO overview</a> describe their controls. Ask each proposed provider to demonstrate a service-page template, a project collection, editable metadata, redirects and the handling of canonical URLs. Then have the intended editor make a real change.</p><p>The deciding factor may be how the content is modelled, which integrations are needed or which tool your support team knows well. A CMS feature list alone is not evidence that one platform will rank a local business above another.</p>'
        if s['title']=='How the controls compare':
            s['body']='<p>Use the same acceptance check in both Framer and Webflow. That gives you a comparison of the proposed implementation instead of a platform popularity contest.</p><table><caption>Local SEO acceptance checks for either platform</caption><thead><tr><th>Requirement</th><th>Demonstration to request</th><th>What the owner learns</th></tr></thead><tbody><tr><td>Titles and descriptions</td><td>Edit an individual service page and a CMS template</td><td>Whether meaningful search text can be maintained</td></tr><tr><td>Headings and page copy</td><td>Show a logical heading order and readable text on mobile</td><td>Whether the design supports the actual explanation</td></tr><tr><td>Redirects and canonical URLs</td><td>Move a sample URL and identify the preferred version</td><td>How old links and duplicate variants will be handled</td></tr><tr><td>Content growth</td><td>Add a project and link it to the right service</td><td>Whether the publishing workflow fits the team</td></tr><tr><td>Structured data</td><td>Show markup that matches the visible business facts</td><td>Who creates and maintains accurate markup</td></tr><tr><td>Indexing and speed</td><td>Check crawl access and test an actual mobile page</td><td>Whether the delivered site meets the technical brief</td></tr></tbody></table>'
        if s['title']=='Which one suits your situation':
            s['body']='<p>For a Kelowna landscaper, begin with the service pages and seasonal projects the team plans to maintain. For a Vernon contractor, include a project page and the quote-request path. A regional professional firm may need a larger library of carefully reviewed explanations. Both platforms deserve evaluation against that real content plan.</p><p>Ask who will edit the site, how often, and what they need to change without a designer. Try publishing one service update and one project in the proposed setup. Include content preparation and support when comparing <a href="/blog/okanagan-website-cost/">website costs in the Okanagan</a>.</p>'
        s['body']=s['body'].replace('Use one per page, matching the page\'s purpose. Do not use multiple H1s.','Use a clear main heading that identifies the page’s purpose and a logical hierarchy below it. This is a readability convention, not a magic ranking rule.').replace('Add LocalBusiness schema with accurate address, phone, and service area. This is custom code work in both platforms.','Use suitable structured data that matches the business facts visible on the page. Do not invent an office address or treat schema as a ranking guarantee.')
    a['faqs'][0]=['Can I switch platforms without losing search traffic?','A migration can affect search performance even when it is carefully planned. Inventory the existing URLs, preserve useful content, map necessary redirects, check canonical and indexing settings, and monitor Search Console after launch. Rebuilding in a different platform is not an SEO reset button.']
    save(a,'Removed unsupported Framer-versus-Webflow scale rankings and rigid H1 rule; replaced feature claims with a practical shared acceptance matrix.')
print(json.dumps(events))
