const treehouse = `<figure class="offer-screen treehouse-frame"><div class="preview-browser-bar">Okanagan Treehouse · interactive preview</div><div class="treehouse-window"><iframe src="/v2/okanagan-preview/index.html" title="Okanagan Treehouse: explore the property, treehouse and cabin" data-service-preview></iframe></div></figure>`;
const rccv = `<figure class="service-laptop"><video autoplay muted loop playsinline preload="metadata" poster="/assets/device-mockups/laptop-three-quarter-rccv-cutout.webp" aria-label="RCCV website design shown on a laptop"><source src="/v2/assets/videos/rccv-showcase-laptop.webm" type="video/webm"><source src="/v2/assets/videos/rccv-showcase-laptop.mp4" type="video/mp4"></video></figure>`;
export function expandPages(pages,{section,columns,screen,link,proof,faq}) {
 const [ai,web,marketing]=pages;
 ai.body=ai.body.replace('<section class="offer-proof page-frame" id="proof">',section('Custom workflows that<br>carry the work forward.','AI implementation means designing the whole process: what starts the work, where the information comes from, who checks it and what happens next.',`<div class="offer-delivery"><article><h3>Enquiries, estimates &amp; follow-up</h3><p>Bring website enquiries into a shared process. Collect the location, service and timing, flag missing details, draft an appropriate reply and create a follow-up task. Your team approves pricing and commitments before they reach a customer.</p></article><article><h3>Proposals &amp; sales preparation</h3><p>Turn an approved brief into a first draft using your services, case studies and pricing rules. Build the proposal, supporting research and presentation together, with a review step before sending.</p></article><article><h3>Marketing production</h3><p>Build a repeatable path from a customer question to a researched brief, draft, images and approved website or campaign content. Keep your brand rules and source material attached to the work.</p></article><article><h3>Reporting &amp; administration</h3><p>Pull agreed data into a recurring report, check for missing inputs and prepare a summary of what changed. Connect handoffs between forms, spreadsheets and business software so someone owns the next action.</p></article></div>`)+ '<section class="offer-proof page-frame" id="proof">');
 const tools=section('Get more from ChatGPT,<br>Claude Cowork and Gemini.','I help your team put the tools into daily use, with your own documents, clear instructions and practical training. We choose the platform around the job and the software you already use.',columns([
 ['ChatGPT setup & training','Organize recurring work with Projects, reference files and instructions. Develop useful drafting, research and analysis routines, then train your team to check sources and review the output.'],
 ['Claude Cowork workflows','Set up repeatable work involving documents, files and connected tools. Define access, task instructions and the approval points for work such as report preparation and sales support.'],
 ['Gemini for your team','Create tailored Gems with instructions and reference material for recurring tasks. Assess where Gemini fits your Google-based working day and where a custom connection is needed.']
 ])+'<p class="offer-note">Available features depend on your plan and workspace settings. Software subscriptions are agreed separately. A custom integration is scoped and tested against your actual tools.</p>');
 ai.body=ai.body.replace('<section class="offer-section page-frame" id="pricing">',tools+section('Someone to keep it working.','Ongoing support includes checking failed runs, updating connections when tools change, reviewing output quality and adjusting the workflow as your team learns what it needs.',columns([['Clear ownership','You know which accounts, subscriptions and documents the system uses. Access and handover are agreed at the start.'],['Practical training','Work through your own examples, leave written instructions and give people a clear way to handle exceptions.'],['A useful measure','Compare response time, preparation time or completed follow-ups against the starting point. Track bookings or enquiries where the data supports it.']]))+'<section class="offer-section page-frame" id="pricing">');
 web.heading='Beautiful websites.<br><em>Built for business.</em>';
 web.description='Okanagan web design and development for distinctive brands and local businesses. Explore Okanagan Treehouse and RCCV, with custom design, SEO and conversion-focused builds.';
 web.hero=treehouse;web.caption='Okanagan Treehouse: the portfolio’s interactive design preview. Scroll inside to explore the stays.';
 web.cta=['Discuss your website','mailto:michael.mckerracher@gmail.com?subject=Website%20consultation','Explore the design','#design-work'];
 web.image='/assets/device-mockups/laptop-three-quarter-rccv-cutout.webp';
 const design=`<section class="offer-section page-frame" id="design-work"><div class="offer-section-heading"><h2>A place you want<br>to spend time in.</h2><div><p>Okanagan Treehouse brings the setting into the website. Moving property imagery, considered type and distinct pages for the treehouse and cabin help a guest picture the stay before making an enquiry.</p><p>The portfolio preview is the design shown here. Explore the full version to see the imagery, transitions and individual accommodation pages.</p><div class="offer-text-links">${link('Explore Okanagan Treehouse','https://okanagan-treehouse-preview.michael-mckerracher.workers.dev/')}${link('View the treehouse stay','https://okanagan-treehouse-preview.michael-mckerracher.workers.dev/stays/treehouse/')}</div></div></div></section><section class="offer-proof page-frame offer-proof-reverse">${rccv}<div class="offer-proof-copy"><h2>Design with a sense<br>of belonging.</h2><p>The RCCV and St. James work brings a school and parish community into a coherent digital experience. Editorial layouts, warm materials and photography give the site a distinct character.</p><p>That visual care sits alongside the everyday task: helping families and parishioners find the information they came for. The design needs to support both the story and the practical visit.</p><div class="offer-text-links">${link('Explore the RCCV project','https://rccv-st-james-limestone-ssr.michael-mckerracher.workers.dev/')}${link('View Stations of the Cross','https://rccv-st-james-limestone-ssr.michael-mckerracher.workers.dev/faith/stations-of-the-cross/')}</div></div></section>`;
 web.body=web.body.replace(/^.*?(?=<section class="offer-section)/s,'');
 web.body=web.body.replace(/<section class="offer-proof page-frame offer-proof-reverse">[\s\S]*?<\/section>/,'');
 web.body=design+web.body;
 web.body=web.body.replace('<section class="offer-section page-frame"><div class="offer-section-heading"><h2>Custom work.',section('Local web design that helps<br>the phone ring.','For a service business, the work starts with what someone is searching for: the service, the area and the problem they need solved. The page needs to answer those questions and make the next step obvious.',columns([['Service pages with substance','Explain the job, who it is for, where you work and what affects an estimate. Include real project photographs, relevant proof and the questions customers ask before calling.'],['Search foundations at launch','Plan page titles, descriptions, internal links, structured data, redirects and a sitemap. Make important content available in HTML and give search engines a clear route through the site.'],['A complete enquiry journey','Connect calls, forms and booking links to the way you handle new business. Check confirmation messages and mobile interactions, then agree how useful enquiries will be measured.']]))+proof()+'<section class="offer-section page-frame"><div class="offer-section-heading"><h2>Custom work.');
 const support=section('Marketing support for<br>being found and chosen.','I work with Okanagan businesses on the parts of marketing that connect discovery to a sale. We can focus on a specific launch, improve your local presence or build a coordinated plan across your website, content and sales materials.',`<div class="offer-delivery"><article><h3>Local SEO &amp; service content</h3><p>Review how customers search for your services in Vernon, Kelowna and the communities you serve. Plan useful service pages, improve internal links and review your Google Business Profile information. Write content around genuine customer questions and the work you can demonstrate.</p></article><article><h3>Brand strategy &amp; messaging</h3><p>Clarify your audience, offer, value proposition and reasons to believe. Turn that into a messaging guide your team can use in website copy, campaigns, proposals and customer conversations.</p></article><article><h3>Visual identity &amp; brand application</h3><p>Establish the typography, colours, imagery and layout direction. Scope the identity work and apply it consistently across the website, presentations and campaign materials people actually see.</p></article><article><h3>Campaign planning &amp; creative</h3><p>Build a campaign around a specific offer and action. Develop the message, landing page, creative and supporting email or social content, with a production plan and defined review steps. Media spend and channel management are scoped separately.</p></article><article><h3>Content &amp; product marketing</h3><p>Explain services and products through demonstrations, customer questions, case studies and useful articles. Create a realistic publishing plan with source material and clear ownership, so the content stays accurate.</p></article><article><h3>Measurement &amp; improvement</h3><p>Agree which calls, enquiries or sales actions matter. Review the available website and campaign data, distinguish traffic from qualified demand and use the findings to choose the next improvement.</p></article></div>`);
 marketing.body=marketing.body.replace('<section class="offer-section page-frame"><div class="offer-section-heading"><h2>Scoped to the work.',support+proof()+section('Work directly with the person<br>who builds the work.','I connect the positioning, writing, design and implementation. You can see the relationship between the recommendation and the finished website, campaign or sales tool.',columns([['A concrete first deliverable','Start with a service page, a campaign or a clearer offer. The proposal names the work, the review points and the cost.'],['Your business as the source','Your customers, existing materials and real projects guide the work. Claims and examples are checked with you before use.'],['Local context','Based in Coldstream, I work with businesses across the Okanagan. We can work through your offer and customer journey together, including on-site sessions where agreed.']]))+faq([['Can you help without a full rebrand?','Yes. We can improve your positioning, website copy, service pages or campaign materials while keeping an identity that already works.'],['Do you offer ongoing marketing support?','Yes, where the scope fits. We agree the recurring deliverables, review schedule and fee in a custom proposal. There is no fixed marketing package or compulsory retainer.'],['Can marketing connect to AI implementation?','Yes. Once the message and process are useful, recurring research, drafting and reporting can become a supported workflow. Human review stays part of customer-facing work.']])+'<section class="offer-section page-frame"><div class="offer-section-heading"><h2>Scoped to the work.');
 marketing.image='/assets/screens/vertical-impression-why-elevators.png';
 for (const [i,p] of pages.entries()) p.body=p.body.replace('<section class="offer-contact">',section('A closer look at the work.','Practical notes on choosing what to build and making it useful.',`<p>${link(articles[i].title,'/blog/'+articles[i].slug+'/')}</p>`)+ '<section class="offer-contact">');
}
const articles=[
{slug:'what-to-automate-first',title:'What should an Okanagan business automate first?',description:'Choose a first AI workflow by looking at recurring work, missing follow-ups and the cost of mistakes.',image:'/assets/screens/vi-automation-proposal.png',service:'/ai-implementation/',sections:[
['Start with work that already has a clear result.','A useful first AI project usually starts with a task your team repeats: preparing an estimate, assembling a proposal, following up an enquiry or producing a weekly report. You should be able to show an example of a good result and name the person who checks it. If nobody agrees what the output should look like, clarify the process before automating it.'],
['Follow one enquiry through the business.','Take a recent customer enquiry and trace what happened. Where did it arrive? Who picked it up? What information was missing? How was an estimate prepared, and who followed up? Write down the waiting time as well as the working time. A five-minute task that sits untouched for two days may matter more than a long task that already runs well.'],
['Compare frequency, effort and consequence.','Make a short list of repeated tasks. For each, record how often it happens, the approximate time it takes, the inputs it needs and the consequence of a wrong result. Proposal preparation may be a good candidate because a person can review the draft. Automatic pricing or customer commitments need tighter rules and more scrutiny. Start with a task where the team can catch mistakes before they cause problems.'],
['Use an existing tool when it covers the job.','ChatGPT Projects can organize files and instructions around recurring work. Gemini Gems can provide tailored instructions and reference material. Claude Cowork can support tasks involving files and connected tools. Those are possible starting points, not a reason to force every process into the same platform. Check your plan, permissions and actual task before selecting a tool.'],
['Build the connections that are missing.','A custom workflow becomes useful when work needs to pass reliably between systems. For example, an enquiry form might create a customer record, assemble a draft proposal and put it into a review queue. Decide what happens when a field is missing or a connection fails. Someone should be able to see the problem and complete the work manually.'],
['Measure the first version before expanding.','Record the starting point and review a representative set of completed work. Compare preparation time, corrections and completed follow-ups. Bookings and revenue can matter too, but changes in demand, pricing and seasonality affect those numbers. Keep the measure close enough to the workflow that you can understand what improved.'],
['What the $900 audit gives you.','My audit includes five on-site hours spread over two to three weeks and a detailed report. We review your current process, prioritize opportunities and identify off-the-shelf options and custom-build recommendations. You can implement the recommendations yourself or discuss ongoing custom implementation and maintenance from $2,500 per month.']
],sources:[['ChatGPT Projects','https://help.openai.com/en/articles/10169521-projects-in-chatgpt'],['Claude Cowork','https://support.claude.com/en/articles/14128542-let-claude-use-your-computer-in-cowork'],['Gemini Gems','https://support.google.com/gemini/answer/15146780']]},
{slug:'website-that-turns-visits-into-enquiries',title:'What makes a local business website worth enquiring through?',description:'A practical website brief covering design, service information, proof and the path from a visit to a call.',image:'/assets/device-mockups/laptop-three-quarter-rccv-cutout.webp',service:'/web-design/',sections:[
['Give the visitor enough to make a decision.','A local business website needs to explain what you do, where you work, why someone should trust you and how to take the next step. Beautiful design helps make the business memorable. Useful information helps someone decide whether to call. The strongest brief brings those two requirements together from the beginning.'],
['Match the experience to the business.','An accommodation website needs to help a guest imagine the stay. The Okanagan Treehouse preview uses property imagery and distinct stories for each accommodation. A school or parish has a different task: communicate its character while making practical information easy to find. The RCCV design puts both into the same experience. A template should not decide what matters most to your customer.'],
['Build service pages around real questions.','For a local service business, describe the work in enough detail that someone can judge the fit. Explain the service area, typical situations, information needed for a quote and anything that affects the scope. Use photographs of real work and relevant examples. A page that only repeats a service name and city has little to help a prospective customer decide.'],
['Put proof beside the claim.','Show the project when discussing design. Link the case study when discussing a business result. In the Cool Runnings case study, the sales increase is attributed to the client report, with separate performance information available for context. Different evidence answers different questions: a finished design demonstrates craft; an enquiry report helps evaluate the customer journey.'],
['Check the complete mobile journey.','Read the page on a phone, tap the contact action and submit the form. Check that labels are visible, fields are usable and the confirmation explains what happens next. Test booking links and phone links. A prominent button is only useful if the process behind it works and someone receives the enquiry.'],
['Plan search and measurement before launch.','Agree the pages and their purpose before writing titles or metadata. Keep important information in readable HTML, link related pages and include canonical pages in a sitemap. Preserve valuable URLs or map redirects during a redesign. Define useful conversion events separately from general visits, then use the available data to review what people actually do.'],
['Bring a business brief, not just a page count.','Tell me who you need to reach, what you want them to do and what is failing on the current site. Bring your existing brand material, photographs and examples of customer questions. I scope the content, design, development and launch work together, with custom pricing based on the actual requirements.']
],sources:[]},
{slug:'local-marketing-plan',title:'A practical marketing plan for an Okanagan service business',description:'Connect positioning, local search, useful content and follow-up to the enquiries your business needs.',image:'/assets/screens/cool-runnings-home.webp',service:'/marketing-branding/',sections:[
['Start with the offer you want people to ask about.','A useful marketing plan begins with a specific service, a clear audience and a next step. Decide what you want to sell more of, where you can deliver it and what makes it a good fit for that customer. That gives your website, search content and campaigns something concrete to explain.'],
['Write down why a customer chooses you.','Look at recent jobs and conversations. What prompted someone to contact you? What did they worry about? What evidence helped them decide? Use those answers to sharpen your positioning. Replace broad claims about quality with details you can show: a relevant project, a clear process, specialist experience or the way you handle a particular job.'],
['Make local discovery consistent.','Review the service information on your website and Google Business Profile together. Check contact details, hours, service areas and the route to an enquiry. Describe the areas you actually serve, including the practical limits. Useful local content should help a customer understand the work; publishing near-identical pages for every town does not create a better buying experience.'],
['Give content a role in the sale.','Choose topics from questions people ask before buying. A case study can demonstrate the finished work. A service page can explain the scope. An article can help someone prepare for an estimate. Connect each piece to the relevant service and contact route. A smaller collection of useful, maintained pages is easier to trust than a large collection of vague articles.'],
['Build a campaign people can act on.','For a seasonal offer or new service, agree the audience, message, destination and action. Prepare the landing page and supporting creative together so the promise stays consistent. Decide who answers enquiries and how quickly they can respond before driving more traffic to the offer. Media spend, production costs and management responsibilities should be explicit in the scope.'],
['Separate attention from useful demand.','Visits and impressions tell you that something was seen. Calls, qualified enquiries and completed bookings tell you more about commercial value. Review these separately, using the data you can actually collect. Compare equivalent periods and account for seasonal changes before attributing a change to a campaign.'],
['Choose the first piece of work.','You may need clearer positioning before a campaign, better service pages before more traffic, or stronger proposals once leads arrive. My marketing and branding work is custom-scoped around that priority. We agree the deliverables, review points, timing and cost, then decide what ongoing support is useful.']
],sources:[]}
];
export function blogPages({section,columns,link}){
 const base={context:'Notes on design, marketing & AI',cta:['Discuss your business','mailto:michael.mckerracher@gmail.com?subject=Free%20initial%20consultation'],caption:'Practical notes from the work, by Michael McKerracher.'};
 const result=articles.map(a=>({...base,path:'/blog/'+a.slug+'/',title:a.title+' | Michael McKerracher',heading:a.title,description:a.description,intro:a.sections[0][1],image:a.image,hero:`<figure class="offer-screen"><img src="${a.image}" alt="${a.slug==='what-to-automate-first'?'Tailored proposal workflow':a.slug==='local-marketing-plan'?'Cool Runnings local service website':'RCCV website presentation'}" width="1440" height="1100"></figure>`,article:true,body:`<article class="blog-body page-frame"><p class="offer-note">By Michael McKerracher · <time datetime="2026-09-25">September 25, 2026</time></p>${a.sections.slice(1).map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}${a.sources.length?`<section><h2>Product references</h2><ul>${a.sources.map(([label,url])=>`<li>${link(label,url)}</li>`).join('')}</ul></section>`:''}<p>${link('Explore the service',a.service)} · ${link('More from the blog','/blog/')}</p></article>`}));
 return [{...base,path:'/blog/',title:'Blog: AI, Web Design & Marketing | Michael McKerracher',heading:'Ideas you can<br><em>put to work.</em>',description:'Practical articles on AI implementation, web design and local marketing for Okanagan businesses.',intro:'What to automate first. What a website needs to earn an enquiry. How to connect your marketing to the work you want more of.',image:'/assets/screens/cool-runnings-home.webp',hero:'<figure class="offer-screen"><img src="/assets/screens/cool-runnings-home.webp" alt="Cool Runnings website, a local business case study" width="1440" height="900"></figure>',body:section('From the work.','Useful starting points for the next decision.',columns(articles.map(a=>[link(a.title,'/blog/'+a.slug+'/'),a.description])))},...result];
}
